apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjobs/backup.yaml
#  - cronjobs/security-scan.yaml
#  - jobs/batch-processor.yaml

namespace: jobs-system
commonLabels:
  managed-by: argocd
  cluster: kubernetes
