apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjobs/backup.yaml
  - jobs/test.yaml

namespace: jobs-system
commonLabels:
  managed-by: argocd
  cluster: kubernetes
